# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
stages:
  # - react-test
  - spring-test
  - dockerize
  - deploy

# cache:
#   paths:
#     - node_modules/

# run react tests:
#   image: node:16.16
#   stage: react-test
#   script: |
#     cd frontend/
#     npm install
#     npm run test
#   only:
#     - master
#     - develop

# run spring tests:
#   image: openjdk:8
#   stage: spring-test
#   script: |
#     cd backend/hool/
#     chmod +x gradlew
#     ./gradlew test
#   only:
#     - master
#     - develop
#     - feature/backend

dockerize:
  image: docker:latest
  stage: dockerize
  services:
    - docker:dind
  before_script: |
    docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script: |
    docker build -t $IMAGE_NAME .
    docker push $IMAGE_NAME
  after_script: |
    docker logout
  only:
    - master

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  tags:
    - deployment
  before_script: |
    docker login -u $DOCKER_HUB_USER --password-stdin < $DOCKER_HUB_PW
  script: |
    cd /opt/openvidu/
    ./openvidu stop
    docker rm $FRONT_CON_NAME
    docker rmi $IMAGE_NAME
    ./openvidu start
  after_script: |
    docker logout
  when: on_success
  only:
    - master
