# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Nodejs.gitlab-ci.yml

# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
stages:
  - react-test
  - spring-test
  - dockerize
  - deploy

# cache:
#   paths:
#     - node_modules/

# run react tests:
#   image: node:16.16
#   stage: react-test
#   script: |
#     cd frontend/
#     npm install --force
#     npm run test
#   only:
#     - master
#     - develop

# run spring tests:
#   image: openjdk:8
#   stage: spring-test
#   script: |
#     cd backend/hool/
#     chmod +x gradlew
#     ./gradlew test
#   only:
#     - master
#     - develop
#     - feature/backend

dockerize:
  image: docker:latest
  stage: dockerize
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script: |
    echo $DOCKER_HUB_PW | docker login -u $DOCKER_HUB_USER --password-stdin
  script: |
    docker build -t $IMAGE_NAME ./frontend/
    docker push $IMAGE_NAME
  after_script: |
    docker logout
  only:
    - master
    - develop

deploy:
  image: docker:latest
  stage: deploy
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  tags:
    - deployment
  before_script: |
    mkdir -p ~/.ssh
    eval $(ssh-agent -s)
    echo $SSH_KNOWN_HOSTS >> ~/.ssh/known_hosts
    chmod 644 ~/.ssh/known_hosts
    chmod 600 $SSH_KEY
    ssh-add $SSH_KEY
  script: |
    ssh ubuntu@"$DEPLOY_SERVER_IP" bash deploy.sh
  after_script: |
    ssh ubuntu@"$DEPLOY_SERVER_IP" docker stop $FRONT_CON_NAME && docker start $FRONT_CON_NAME
  when: on_success
  only:
    - master
    - develop
