stages:
  - spring-build
  - spring-package
  - spring-deploy

spring-build:
  image: java:8-jdk
  stage: spring-build
  script:
    - ./gradlew clean
    - ./gradlew build - x test
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 10 min
  only: 
    - master
    - develop
    - feature/backend

spring-package:
  image: docker:latest
  stage: spring-package
  services:
    - docker:dind
  before_script: |
    docker login -u $DOCKER_HUB_USER_BACK --password-stdin < $DOCKER_HUB_PW_BACK
  script: |
    docker build -t $IMAGE_NAME_BACK .
    docker push $IMAGE_NAME_BACK
  after_script: |
    docker logout
  only:
    - master
    - develop
    - feature/backend
