version: "3"
services:
  database:
    image: mysql:8.0.29
    container_name: ssafy_web_db
    environment:
      - MYSQL_DATABASE=ssafy_web_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=(2MdiTE7h[BXy(fEVQw=
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306
    volumes:
      - /home/revision/docker_spring/database/ssafy_web_db/:/var/lib/mysql
    networks:
      - test_network_02
  application:
    image: hooltest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis
    container_name: app_test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/ssafy_web_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: (2MdiTE7h[BXy(fEVQw=
    networks:
      - test_network_02
  redis:
    image: localhost
    ports:
      - 6379:6379
    container_name: redis
    networks:
      - test_network_02

networks:
  test_network_02: