name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
      - name: Run scripts
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/SSH_KEY.key
          chmod 600 ~/.ssh/SSH_KEY.key
          ssh-add ~/.ssh/SSH_KEY.key
          ssh ubuntu@"${{ secrets.DEPLOY_SERVER_IP }}" sudo bash deploy.sh
