name: Spring CI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
#       - name: Cache dependency
#         uses: actions/cache@v2
#         with:
#           path: ~/.cache/pip
#           key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
#           restore-keys: |
#             ${{ runner.os }}-pip-

#       - name: Create secrets
#         run: echo "${{ secrets.DOTENV }}" > server/.env

      - name: Set up Java JDK
        uses: actions/setup-java@v3.4.1
        with: 
          java-version: '8'
          distribution: temurin

      - name: Build
        run: |
            echo -e ${{ BACK_APIKEY }} > ./backend/hool/src/main/resources/application-API-KEY.properties
            value=`cat ./backend/hool/src/main/resources/application-API-KEY.properties`
            echo "$value"
            cd backend/hool/
            chmod +x gradlew
            ./gradlew build -x test

      - name: Dockerize
        run: |
          echo "${{ secrets.BACK_DOCKER_HUB_PW }}" | docker login -u "${{ secrets.BACK_DOCKER_HUB_USER }}" --password-stdin
          docker build -t "${{ secrets.BACK_IMAGE_NAME }}" ./backend/hool
          docker push "${{ secrets.BACK_IMAGE_NAME }}"
          docker logout
